"""empty message

Revision ID: 3240a0d134b4
Revises: 
Create Date: 2019-02-06 15:44:50.547118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3240a0d134b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomnumber', sa.String(), nullable=True),
    sa.Column('ranges', sa.String(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('building')
    # ### end Alembic commands ###
